### ISSUE TITLE
Setup and command line tool

### ISSUE THREAD

**Issue by gorgobacka** [sonovice/smude#6]
It would be useful, if the package can be installed with a setup.py that already installs all requirements. The first time I had problems to figure out the correct packages.

Additionally, I would like to use your tool direct on the command line and provide the images via parameters.

Something like:
smude -i input_image -o output_image

As far as I know, you need a main() function as entry point.

What do you think?

If I find some free time, I can create a PR.

**Comment by sonovice** [comment]
That does indeed sound useful and a PR would be very welcome!
